name: pythontools
channels:
  - conda-forge
dependencies:
  - conda
  - python
  - setuptools
  - ipython
  - pip
  - jupyter
  - notebook
  - pytest
  - sphinx=3.2
  - numpydoc
  - sphinx-argparse
  - nbsphinx
  - numpy=1.19
  - matplotlib=3.3
  - openturns
  - otmorris
  - pandas=1.1